version: "3.2"
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    volumes:
      - ./postgresql/data/:/var/lib/postgresql/data/
    env_file: ".env"
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASS}
      - POSTGRES_HOST_AUTH_METHOD=trust
    hostname: ${DATABASE_HOST}
    ports:
      - ${DATABASE_PORT}:${DATABASE_PORT}
    restart: always

  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    environment:
      - TZ=Europe/Minsk
    ports:
      - "1880:1880"
    volumes:
      - ./node-red/data:/data
    restart: always

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - ./influxdb2:/var/lib/influxdb2:rw
    ports:
      - "8086:8086"
    environment:
      - TZ=Etc/UTC
      - DOCKER_INFLUXDB_INIT_USERNAME=xlink
      - DOCKER_INFLUXDB_INIT_PASSWORD=xlink1234
      - DOCKER_INFLUXDB_INIT_ORG=xlink
      - DOCKER_INFLUXDB_INIT_BUCKET=xlink
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=xlink
      - DOCKER_INFLUXDB_INIT_MODE=setup
      # - DOCKER_INFLUXDB_INIT_MODE=upgrade
    restart: always

  rabbitmq:
    image: rabbitmq:3
    container_name: rabbitmq
    volumes:
      - ./rabbitmq/etc/rabbitmq:/etc/rabbitmq
      - ./rabbitmq/var/lib/rabbitmq/:/var/lib/rabbitmq/
      - ./rabbitmq/var/log/rabbitmq/:/var/log/rabbitmq
    environment:
      - "RABBITMQ_DEFAULT_USER=xlink"
      - "RABBITMQ_DEFAULT_PASS=xlink"
      - "RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648"
    restart: always
    hostname: localhost
    ports:
      - "1883:1883"
      - "5672:5672"
      - "15672:15672"
      - "15675:15675"

#  pgadmin:
#    image: dpage/pgadmin4
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=root
#    ports:
#      - "8080:80"

#  telegraf:
#    image: telegraf:latest
#    container_name: telegraf
#    volumes:
#      - ./telegraf/telegraf.conf:/etc/telegraf/telegraf.conf:ro
#    links:
#      - influxdb
#    restart: always
#    depends_on:
#      - influxdb
#    ports:
#      - "8125:8125"

#  kapacitor:
#    image: kapacitor:latest
#    container_name: kapacitor
#    volumes:
#      - ./kapacitor/data/:/var/lib/kapacitor
#      - ./kapacitor/config/:/etc/kapacitor/
#    links:
#      - influxdb
#    ports:
#      - "9092:9092"
#    networks:
#      - tignet

#  chronograf:
#    image: chronograf:latest
#    container_name: chronograf
#    restart: always
#    ports:
#      - "8888:8888"
#    depends_on:
#      - kapacitor
#      - influxdb
#      - telegraf
#    environment:
#      - INFLUXDB_URL=http://influxdb:8086
#      - INFLUXDB_USERNAME=xlink
#      - INFLUXDB_PASSWORD=xlink1234
#    volumes:
#      - ./chronograf/data/:/var/lib/chronograf/
#    links:
#      - influxdb
#      - kapacitor
#    networks:
#      - tignet

#  grafana:
#    image: grafana/grafana:latest
#    container_name: grafana
#    ports:
#      - "3000:3000"
#    user: "0"
#    links:
#      - influxdb
#    volumes:
#      # sudo mkdir -p /srv/docker/grafana/data; chown 472:472 /srv/docker/grafana/data
#      - ./grafana:/var/lib/grafana


